# Dependabot auto-updates action versions in your workflows.
# https://docs.github.com/en/code-security/dependabot
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-deps:
        patterns:
          - "*"
