include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    # TODO(eseidel): Remove this and fix all discarded futures.
    discarded_futures: false