# cspell:words carryforward
# Added to cause Shorebird CI to run coverage.
codecov: 
 token: 23aa30e2-c969-4deb-a659-5affc5892245

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true