// GENERATED FILE - DO NOT EDIT
//
// Generated by: dart run tool/generate_modifier_names.dart
//
// This file contains the ModifiersBase class with typed getters for all
// modifier names found in the Melvor Idle JSON data files.

import 'package:meta/meta.dart';

/// Base class providing typed access to modifier values.
///
/// Provides getters for all known modifier names. Values default to 0
/// when not present in the underlying map.
@immutable
class ModifiersBase {
  const ModifiersBase(this.values);

  /// The underlying modifier values map.
  final Map<String, num> values;

  /// True if no modifiers are present.
  bool get isEmpty => values.isEmpty;

  num get accuracyRating => values['accuracyRating'] ?? 0;
  num get additionalItemBasedOnPrimaryQuantityChance =>
      values['additionalItemBasedOnPrimaryQuantityChance'] ?? 0;
  num get additionalPrimaryProductChance =>
      values['additionalPrimaryProductChance'] ?? 0;
  num get additionalRandomGemChance => values['additionalRandomGemChance'] ?? 0;
  num get additionalRandomSkillItemChance =>
      values['additionalRandomSkillItemChance'] ?? 0;
  num get agilityItemCostReductionCanReach100 =>
      values['agilityItemCostReductionCanReach100'] ?? 0;
  num get agilityObstacleCost => values['agilityObstacleCost'] ?? 0;
  num get agilityObstacleItemCost => values['agilityObstacleItemCost'] ?? 0;
  num get allowAttackAugmentingMagic =>
      values['allowAttackAugmentingMagic'] ?? 0;
  num get allowLootContainerStacking =>
      values['allowLootContainerStacking'] ?? 0;
  num get allowSignetDrops => values['allowSignetDrops'] ?? 0;
  num get altMagicRunePreservationChance =>
      values['altMagicRunePreservationChance'] ?? 0;
  num get altMagicSkillXP => values['altMagicSkillXP'] ?? 0;
  num get ammoPreservationChance => values['ammoPreservationChance'] ?? 0;
  num get attackInterval => values['attackInterval'] ?? 0;
  num get attackRolls => values['attackRolls'] ?? 0;
  num get autoBurying => values['autoBurying'] ?? 0;
  num get autoEatEfficiency => values['autoEatEfficiency'] ?? 0;
  num get autoEatHPLimit => values['autoEatHPLimit'] ?? 0;
  num get autoEatThreshold => values['autoEatThreshold'] ?? 0;
  num get autoEquipFoodUnlocked => values['autoEquipFoodUnlocked'] ?? 0;
  num get autoLooting => values['autoLooting'] ?? 0;
  num get autoSlayerUnlocked => values['autoSlayerUnlocked'] ?? 0;
  num get autoSwapFoodUnlocked => values['autoSwapFoodUnlocked'] ?? 0;
  num get bankSpace => values['bankSpace'] ?? 0;
  num get basePrimaryProductQuantity =>
      values['basePrimaryProductQuantity'] ?? 0;
  num get bleedLifesteal => values['bleedLifesteal'] ?? 0;
  num get bonusCoalMining => values['bonusCoalMining'] ?? 0;
  num get bonusCoalOnDungeonCompletion =>
      values['bonusCoalOnDungeonCompletion'] ?? 0;
  num get bonusFishingSpecialChance => values['bonusFishingSpecialChance'] ?? 0;
  num get burnLifesteal => values['burnLifesteal'] ?? 0;
  num get bypassSlayerItems => values['bypassSlayerItems'] ?? 0;
  num get cannotFishJunk => values['cannotFishJunk'] ?? 0;
  num get cantAttack => values['cantAttack'] ?? 0;
  num get cantEvade => values['cantEvade'] ?? 0;
  num get cantRegenBarrier => values['cantRegenBarrier'] ?? 0;
  num get cartographyMapUpgradeInterval =>
      values['cartographyMapUpgradeInterval'] ?? 0;
  num get cartographyPaperMakingInterval =>
      values['cartographyPaperMakingInterval'] ?? 0;
  num get cartographySurveyInterval => values['cartographySurveyInterval'] ?? 0;
  num get combatLootDoublingChance => values['combatLootDoublingChance'] ?? 0;
  num get compostPreservationChance => values['compostPreservationChance'] ?? 0;
  num get convertBoneDropsIntoCake => values['convertBoneDropsIntoCake'] ?? 0;
  num get cookingSuccessCap => values['cookingSuccessCap'] ?? 0;
  num get currencyGain => values['currencyGain'] ?? 0;
  num get currencyGainFromCombat => values['currencyGainFromCombat'] ?? 0;
  num get currencyGainFromLifesteal => values['currencyGainFromLifesteal'] ?? 0;
  num get currencyGainFromLogSales => values['currencyGainFromLogSales'] ?? 0;
  num get currencyGainFromMonsterDrops =>
      values['currencyGainFromMonsterDrops'] ?? 0;
  num get currencyGainFromSlayerTaskMonsterDrops =>
      values['currencyGainFromSlayerTaskMonsterDrops'] ?? 0;
  num get currencyGainOnMonsterKillBasedOnEvasion =>
      values['currencyGainOnMonsterKillBasedOnEvasion'] ?? 0;
  num get currencyGainOnRegenBasedOnHPGained =>
      values['currencyGainOnRegenBasedOnHPGained'] ?? 0;
  num get currencyGainPerDamageDealtBasedOnCurrencyAmount =>
      values['currencyGainPerDamageDealtBasedOnCurrencyAmount'] ?? 0;
  num get currencyGainPerMagicDamageDealt =>
      values['currencyGainPerMagicDamageDealt'] ?? 0;
  num get currencyGainPerMagicDamageDealtOnSlayerTask =>
      values['currencyGainPerMagicDamageDealtOnSlayerTask'] ?? 0;
  num get currencyGainPerMeleeDamageDealt =>
      values['currencyGainPerMeleeDamageDealt'] ?? 0;
  num get currencyGainPerRangedDamageDealt =>
      values['currencyGainPerRangedDamageDealt'] ?? 0;
  num get currentHPDamageTakenOnAttack =>
      values['currentHPDamageTakenOnAttack'] ?? 0;
  num get damageDealt => values['damageDealt'] ?? 0;
  num get damageDealtToAllMonsters => values['damageDealtToAllMonsters'] ?? 0;
  num get damageDealtToBosses => values['damageDealtToBosses'] ?? 0;
  num get damageDealtToMonstersInArea =>
      values['damageDealtToMonstersInArea'] ?? 0;
  num get damageDealtToSlayerTasks => values['damageDealtToSlayerTasks'] ?? 0;
  num get damageTaken => values['damageTaken'] ?? 0;
  num get disableAttackDamage => values['disableAttackDamage'] ?? 0;
  num get doubleItemsSkill => values['doubleItemsSkill'] ?? 0;
  num get doubleRuneProvision => values['doubleRuneProvision'] ?? 0;
  num get dragonBreathDamage => values['dragonBreathDamage'] ?? 0;
  num get dungeonEquipmentSwapping => values['dungeonEquipmentSwapping'] ?? 0;
  num get effectIgnoreChance => values['effectIgnoreChance'] ?? 0;
  num get effectImmunity => values['effectImmunity'] ?? 0;
  num get elementalRuneChance => values['elementalRuneChance'] ?? 0;
  num get elementalRuneQuantity => values['elementalRuneQuantity'] ?? 0;
  num get enableNightfallSeason => values['enableNightfallSeason'] ?? 0;
  num get equipmentAttackSpeed => values['equipmentAttackSpeed'] ?? 0;
  num get equipmentSets => values['equipmentSets'] ?? 0;
  num get evasion => values['evasion'] ?? 0;
  num get farmingCropsCannotDie => values['farmingCropsCannotDie'] ?? 0;
  num get farmingSeedReturn => values['farmingSeedReturn'] ?? 0;
  num get firemakingBonfireInterval => values['firemakingBonfireInterval'] ?? 0;
  num get firemakingLogCurrencyGain => values['firemakingLogCurrencyGain'] ?? 0;
  num get fishingAdditionalSpecialItemChance =>
      values['fishingAdditionalSpecialItemChance'] ?? 0;
  num get fishingCookedChance => values['fishingCookedChance'] ?? 0;
  num get fishingMasteryDoublingChance =>
      values['fishingMasteryDoublingChance'] ?? 0;
  num get fishingSpecialChance => values['fishingSpecialChance'] ?? 0;
  num get flatAdditionalPrimaryProductQuantity =>
      values['flatAdditionalPrimaryProductQuantity'] ?? 0;
  num get flatAdditionalSkillItem => values['flatAdditionalSkillItem'] ?? 0;
  num get flatAttackInterval => values['flatAttackInterval'] ?? 0;
  num get flatBasePrimaryProductQuantity =>
      values['flatBasePrimaryProductQuantity'] ?? 0;
  num get flatBasePrimaryProductQuantityChance =>
      values['flatBasePrimaryProductQuantityChance'] ?? 0;
  num get flatBaseRandomProductQuantity =>
      values['flatBaseRandomProductQuantity'] ?? 0;
  num get flatBlockAttackBonus => values['flatBlockAttackBonus'] ?? 0;
  num get flatCoalGainedOnCookingFailure =>
      values['flatCoalGainedOnCookingFailure'] ?? 0;
  num get flatCraftingDragonhideCost =>
      values['flatCraftingDragonhideCost'] ?? 0;
  num get flatCurrencyGainFromMonsterDrops =>
      values['flatCurrencyGainFromMonsterDrops'] ?? 0;
  num get flatCurrencyGainOnEnemyHit =>
      values['flatCurrencyGainOnEnemyHit'] ?? 0;
  num get flatCurrencyGainWhenHitBasedOnResistance =>
      values['flatCurrencyGainWhenHitBasedOnResistance'] ?? 0;
  num get flatFarmingSeedCost => values['flatFarmingSeedCost'] ?? 0;
  num get flatHPRegen => values['flatHPRegen'] ?? 0;
  num get flatHPRegenBasedOnMagicMaxHit =>
      values['flatHPRegenBasedOnMagicMaxHit'] ?? 0;
  num get flatHPRegenBasedOnMeleeMaxHit =>
      values['flatHPRegenBasedOnMeleeMaxHit'] ?? 0;
  num get flatHPRegenBasedOnRangedMaxHit =>
      values['flatHPRegenBasedOnRangedMaxHit'] ?? 0;
  num get flatHiddenSkillLevel => values['flatHiddenSkillLevel'] ?? 0;
  num get flatMagicAttackBonus => values['flatMagicAttackBonus'] ?? 0;
  num get flatMagicDefenceBonus => values['flatMagicDefenceBonus'] ?? 0;
  num get flatMagicMaxHit => values['flatMagicMaxHit'] ?? 0;
  num get flatMagicMinHit => values['flatMagicMinHit'] ?? 0;
  num get flatMasteryTokens => values['flatMasteryTokens'] ?? 0;
  num get flatMaxHit => values['flatMaxHit'] ?? 0;
  num get flatMaxHitpoints => values['flatMaxHitpoints'] ?? 0;
  num get flatMeleeDefenceBonus => values['flatMeleeDefenceBonus'] ?? 0;
  num get flatMeleeDefenceBonusBasedOnResistance =>
      values['flatMeleeDefenceBonusBasedOnResistance'] ?? 0;
  num get flatMeleeStrengthBonus => values['flatMeleeStrengthBonus'] ?? 0;
  num get flatMinHit => values['flatMinHit'] ?? 0;
  num get flatMiningNodeHP => values['flatMiningNodeHP'] ?? 0;
  num get flatMonsterRespawnInterval =>
      values['flatMonsterRespawnInterval'] ?? 0;
  num get flatPotionCharges => values['flatPotionCharges'] ?? 0;
  num get flatPrayerPointCost => values['flatPrayerPointCost'] ?? 0;
  num get flatRangedAttackBonus => values['flatRangedAttackBonus'] ?? 0;
  num get flatRangedDefenceBonus => values['flatRangedDefenceBonus'] ?? 0;
  num get flatRangedDefenceBonusBasedOnResistance =>
      values['flatRangedDefenceBonusBasedOnResistance'] ?? 0;
  num get flatRangedStrengthBonus => values['flatRangedStrengthBonus'] ?? 0;
  num get flatReflectDamage => values['flatReflectDamage'] ?? 0;
  num get flatRegenerationInterval => values['flatRegenerationInterval'] ?? 0;
  num get flatResistance => values['flatResistance'] ?? 0;
  num get flatResistanceAgainstMagic =>
      values['flatResistanceAgainstMagic'] ?? 0;
  num get flatResistanceAgainstMelee =>
      values['flatResistanceAgainstMelee'] ?? 0;
  num get flatResistanceAgainstRanged =>
      values['flatResistanceAgainstRanged'] ?? 0;
  num get flatResistanceAgainstSlayerTasks =>
      values['flatResistanceAgainstSlayerTasks'] ?? 0;
  num get flatSkillInterval => values['flatSkillInterval'] ?? 0;
  num get flatSlashAttackBonus => values['flatSlashAttackBonus'] ?? 0;
  num get flatSlayerAreaEffectNegation =>
      values['flatSlayerAreaEffectNegation'] ?? 0;
  num get flatSmithingCoalCost => values['flatSmithingCoalCost'] ?? 0;
  num get flatStabAttackBonus => values['flatStabAttackBonus'] ?? 0;
  num get flatSummoningShardCost => values['flatSummoningShardCost'] ?? 0;
  num get flatThievingCurrencyGain => values['flatThievingCurrencyGain'] ?? 0;
  num get flatTier1SummoningShardCost =>
      values['flatTier1SummoningShardCost'] ?? 0;
  num get flatTier2SummoningShardCost =>
      values['flatTier2SummoningShardCost'] ?? 0;
  num get flatTier3SummoningShardCost =>
      values['flatTier3SummoningShardCost'] ?? 0;
  num get flatTownshipEducation => values['flatTownshipEducation'] ?? 0;
  num get flatTownshipHappiness => values['flatTownshipHappiness'] ?? 0;
  num get foodHealingValue => values['foodHealingValue'] ?? 0;
  num get foodPreservationChance => values['foodPreservationChance'] ?? 0;
  num get freeBonfires => values['freeBonfires'] ?? 0;
  num get freeProtectItem => values['freeProtectItem'] ?? 0;
  num get giveRandomComboRunesRunecrafting =>
      values['giveRandomComboRunesRunecrafting'] ?? 0;
  num get globalEvasionHPScaling => values['globalEvasionHPScaling'] ?? 0;
  num get globalItemDoublingChance => values['globalItemDoublingChance'] ?? 0;
  num get golbinRaidMaximumAmmo => values['golbinRaidMaximumAmmo'] ?? 0;
  num get golbinRaidMaximumRunes => values['golbinRaidMaximumRunes'] ?? 0;
  num get golbinRaidMinimumFood => values['golbinRaidMinimumFood'] ?? 0;
  num get golbinRaidPassiveSlotUnlocked =>
      values['golbinRaidPassiveSlotUnlocked'] ?? 0;
  num get golbinRaidPrayerLevel => values['golbinRaidPrayerLevel'] ?? 0;
  num get golbinRaidPrayerPointsPerWave =>
      values['golbinRaidPrayerPointsPerWave'] ?? 0;
  num get golbinRaidPrayerUnlocked => values['golbinRaidPrayerUnlocked'] ?? 0;
  num get golbinRaidStartingPrayerPoints =>
      values['golbinRaidStartingPrayerPoints'] ?? 0;
  num get golbinRaidStartingRuneCount =>
      values['golbinRaidStartingRuneCount'] ?? 0;
  num get golbinRaidStartingWeapon => values['golbinRaidStartingWeapon'] ?? 0;
  num get golbinRaidWaveSkipCost => values['golbinRaidWaveSkipCost'] ?? 0;
  num get halveAgilityObstacleNegatives =>
      values['halveAgilityObstacleNegatives'] ?? 0;
  num get halveWoodcuttingDoubleChance =>
      values['halveWoodcuttingDoubleChance'] ?? 0;
  num get healingOnAttackBasedOnResistance =>
      values['healingOnAttackBasedOnResistance'] ?? 0;
  num get hitpointRegeneration => values['hitpointRegeneration'] ?? 0;
  num get hitpointRegenerationAgainstSlayerTasks =>
      values['hitpointRegenerationAgainstSlayerTasks'] ?? 0;
  num get hpRegenWhenEnemyHasMoreEvasion =>
      values['hpRegenWhenEnemyHasMoreEvasion'] ?? 0;
  num get ignoreThievingDamage => values['ignoreThievingDamage'] ?? 0;
  num get itemProtection => values['itemProtection'] ?? 0;
  num get lifesteal => values['lifesteal'] ?? 0;
  num get magicAccuracyRating => values['magicAccuracyRating'] ?? 0;
  num get magicCritChance => values['magicCritChance'] ?? 0;
  num get magicDamageBonus => values['magicDamageBonus'] ?? 0;
  num get magicEvasion => values['magicEvasion'] ?? 0;
  num get magicImmunity => values['magicImmunity'] ?? 0;
  num get magicLifesteal => values['magicLifesteal'] ?? 0;
  num get magicMaxHit => values['magicMaxHit'] ?? 0;
  num get magicMinHitBasedOnMaxHit => values['magicMinHitBasedOnMaxHit'] ?? 0;
  num get magicMinHitBasedOnMaxHitSlayerTask =>
      values['magicMinHitBasedOnMaxHitSlayerTask'] ?? 0;
  num get magicProtection => values['magicProtection'] ?? 0;
  num get masteryPoolCap => values['masteryPoolCap'] ?? 0;
  num get masteryXP => values['masteryXP'] ?? 0;
  num get maxCurrencyMultiplierPerDamage =>
      values['maxCurrencyMultiplierPerDamage'] ?? 0;
  num get maxHit => values['maxHit'] ?? 0;
  num get maxHitpoints => values['maxHitpoints'] ?? 0;
  num get meleeAccuracyRating => values['meleeAccuracyRating'] ?? 0;
  num get meleeCritChance => values['meleeCritChance'] ?? 0;
  num get meleeEvasion => values['meleeEvasion'] ?? 0;
  num get meleeImmunity => values['meleeImmunity'] ?? 0;
  num get meleeLifesteal => values['meleeLifesteal'] ?? 0;
  num get meleeMaxHit => values['meleeMaxHit'] ?? 0;
  num get meleeMinHitBasedOnMaxHitSlayerTask =>
      values['meleeMinHitBasedOnMaxHitSlayerTask'] ?? 0;
  num get meleeProtection => values['meleeProtection'] ?? 0;
  num get meleeStrengthBonus => values['meleeStrengthBonus'] ?? 0;
  num get meteoriteLocationChance => values['meteoriteLocationChance'] ?? 0;
  num get minCurrencyMultiplierPerDamage =>
      values['minCurrencyMultiplierPerDamage'] ?? 0;
  num get minHitBasedOnMaxHit => values['minHitBasedOnMaxHit'] ?? 0;
  num get minThievingCurrencyGain => values['minThievingCurrencyGain'] ?? 0;
  num get miningBarChance => values['miningBarChance'] ?? 0;
  num get miningGemChance => values['miningGemChance'] ?? 0;
  num get miningNodeRespawnInterval => values['miningNodeRespawnInterval'] ?? 0;
  num get noMiningNodeDamageChance => values['noMiningNodeDamageChance'] ?? 0;
  num get nonCombatSkillXP => values['nonCombatSkillXP'] ?? 0;
  num get nonShardSummoningCostReduction =>
      values['nonShardSummoningCostReduction'] ?? 0;
  num get offItemChance => values['offItemChance'] ?? 0;
  num get onHitSlowMagnitude => values['onHitSlowMagnitude'] ?? 0;
  num get otherStyleImmunity => values['otherStyleImmunity'] ?? 0;
  num get perfectCookChance => values['perfectCookChance'] ?? 0;
  num get poisonLifesteal => values['poisonLifesteal'] ?? 0;
  num get potionChargePreservationChance =>
      values['potionChargePreservationChance'] ?? 0;
  num get potionCharges => values['potionCharges'] ?? 0;
  num get prayerPointCost => values['prayerPointCost'] ?? 0;
  num get prayerPointPreservationChance =>
      values['prayerPointPreservationChance'] ?? 0;
  num get randomHerblorePotionChance =>
      values['randomHerblorePotionChance'] ?? 0;
  num get randomProductChance => values['randomProductChance'] ?? 0;
  num get rangedAccuracyRating => values['rangedAccuracyRating'] ?? 0;
  num get rangedCritChance => values['rangedCritChance'] ?? 0;
  num get rangedEvasion => values['rangedEvasion'] ?? 0;
  num get rangedImmunity => values['rangedImmunity'] ?? 0;
  num get rangedLifesteal => values['rangedLifesteal'] ?? 0;
  num get rangedMaxHit => values['rangedMaxHit'] ?? 0;
  num get rangedMinHitBasedOnMaxHitSlayerTask =>
      values['rangedMinHitBasedOnMaxHitSlayerTask'] ?? 0;
  num get rangedProtection => values['rangedProtection'] ?? 0;
  num get rangedStrengthBonus => values['rangedStrengthBonus'] ?? 0;
  num get rebirthChance => values['rebirthChance'] ?? 0;
  num get reflectDamage => values['reflectDamage'] ?? 0;
  num get resistance => values['resistance'] ?? 0;
  num get rolledReflectDamage => values['rolledReflectDamage'] ?? 0;
  num get runePreservationChance => values['runePreservationChance'] ?? 0;
  num get runecraftingBaseXPForRunes =>
      values['runecraftingBaseXPForRunes'] ?? 0;
  num get runecraftingRuneCostReduction =>
      values['runecraftingRuneCostReduction'] ?? 0;
  num get seedDropConversionChance => values['seedDropConversionChance'] ?? 0;
  num get skillInterval => values['skillInterval'] ?? 0;
  num get skillItemDoublingChance => values['skillItemDoublingChance'] ?? 0;
  num get skillPreservationCap => values['skillPreservationCap'] ?? 0;
  num get skillPreservationChance => values['skillPreservationChance'] ?? 0;
  num get skillXP => values['skillXP'] ?? 0;
  num get slayerTaskLength => values['slayerTaskLength'] ?? 0;
  num get smithingCoalCost => values['smithingCoalCost'] ?? 0;
  num get strongholdEquipmentSwapping =>
      values['strongholdEquipmentSwapping'] ?? 0;
  num get stunDurationIncreaseChance =>
      values['stunDurationIncreaseChance'] ?? 0;
  num get successfulCookChance => values['successfulCookChance'] ?? 0;
  num get summoningAttackInterval => values['summoningAttackInterval'] ?? 0;
  num get summoningAttackLifesteal => values['summoningAttackLifesteal'] ?? 0;
  num get summoningChargePreservationChance =>
      values['summoningChargePreservationChance'] ?? 0;
  num get summoningMaxHit => values['summoningMaxHit'] ?? 0;
  num get summoningSynergy45 => values['summoningSynergy_4_5'] ?? 0;
  num get summoningSynergyEntLeprechaun =>
      values['summoningSynergy_Ent_Leprechaun'] ?? 0;
  num get summoningSynergyLeprechaunDevil =>
      values['summoningSynergy_Leprechaun_Devil'] ?? 0;
  num get summoningSynergyOctopusLeprechaun =>
      values['summoningSynergy_Octopus_Leprechaun'] ?? 0;
  num get thievingAreaUniqueChancePercent =>
      values['thievingAreaUniqueChancePercent'] ?? 0;
  num get thievingAutoSellPrice => values['thievingAutoSellPrice'] ?? 0;
  num get thievingFarmerHerbSackChance =>
      values['thievingFarmerHerbSackChance'] ?? 0;
  num get thievingMinerRandomBarChance =>
      values['thievingMinerRandomBarChance'] ?? 0;
  num get thievingStealth => values['thievingStealth'] ?? 0;
  num get townshipBuildingCost => values['townshipBuildingCost'] ?? 0;
  num get townshipBuildingProduction =>
      values['townshipBuildingProduction'] ?? 0;
  num get townshipGPProduction => values['townshipGPProduction'] ?? 0;
  num get townshipMaxStorage => values['townshipMaxStorage'] ?? 0;
  num get townshipRepairCost => values['townshipRepairCost'] ?? 0;
  num get townshipResourceProduction =>
      values['townshipResourceProduction'] ?? 0;
  num get townshipTaxPerCitizen => values['townshipTaxPerCitizen'] ?? 0;
  num get townshipTraderCost => values['townshipTraderCost'] ?? 0;
  num get treeCutLimit => values['treeCutLimit'] ?? 0;
  num get woodcuttingJewelryChance => values['woodcuttingJewelryChance'] ?? 0;
  num get woodcuttingXPAddedAsFiremakingXP =>
      values['woodcuttingXPAddedAsFiremakingXP'] ?? 0;
}
