// GENERATED FILE - DO NOT EDIT
//
// Generated by: dart run tool/generate_modifier_names.dart
//
// This file contains:
// - ModifierAccessors: typed methods for ModifierProvider

import 'package:logic/src/data/melvor_id.dart';
import 'package:meta/meta.dart';

/// Mixin providing typed modifier accessor methods.
///
/// Generated from Melvor Idle JSON data. Each method wraps
/// the internal getModifier() call with appropriate scope parameters.
///
/// Scope parameters are marked required when the modifier
/// always uses that scope field in the source data.
mixin ModifierAccessors {
  /// Internal method to get a modifier value by name and scope.
  /// Implemented by ModifierProvider - walks all modifier sources.
  @protected
  num getModifier(
    String name, {
    MelvorId? skillId,
    MelvorId? actionId,
    MelvorId? itemId,
    MelvorId? categoryId,
  });

  int get accuracyRating => getModifier('accuracyRating').toInt();
  int additionalItemBasedOnPrimaryQuantityChance({
    required MelvorId skillId,
    required MelvorId actionId,
    required MelvorId itemId,
  }) => getModifier(
    'additionalItemBasedOnPrimaryQuantityChance',
    skillId: skillId,
    actionId: actionId,
    itemId: itemId,
  ).toInt();
  int additionalPrimaryProductChance({required MelvorId skillId}) =>
      getModifier('additionalPrimaryProductChance', skillId: skillId).toInt();
  int additionalRandomGemChance({
    required MelvorId skillId,
    MelvorId? actionId,
  }) => getModifier(
    'additionalRandomGemChance',
    skillId: skillId,
    actionId: actionId,
  ).toInt();
  int additionalRandomSkillItemChance({
    required MelvorId skillId,
    required MelvorId itemId,
    MelvorId? actionId,
  }) => getModifier(
    'additionalRandomSkillItemChance',
    skillId: skillId,
    actionId: actionId,
    itemId: itemId,
  ).toInt();
  int get agilityItemCostReductionCanReach100 =>
      getModifier('agilityItemCostReductionCanReach100').toInt();
  int agilityObstacleCost({MelvorId? actionId}) =>
      getModifier('agilityObstacleCost', actionId: actionId).toInt();
  int get agilityObstacleItemCost =>
      getModifier('agilityObstacleItemCost').toInt();
  int get allowAttackAugmentingMagic =>
      getModifier('allowAttackAugmentingMagic').toInt();
  int get allowLootContainerStacking =>
      getModifier('allowLootContainerStacking').toInt();
  int get allowSignetDrops => getModifier('allowSignetDrops').toInt();
  int get altMagicRunePreservationChance =>
      getModifier('altMagicRunePreservationChance').toInt();
  int get altMagicSkillXP => getModifier('altMagicSkillXP').toInt();
  int get ammoPreservationChance =>
      getModifier('ammoPreservationChance').toInt();
  int get attackInterval => getModifier('attackInterval').toInt();
  int get attackRolls => getModifier('attackRolls').toInt();
  int get autoBurying => getModifier('autoBurying').toInt();
  int get autoEatEfficiency => getModifier('autoEatEfficiency').toInt();
  int get autoEatHPLimit => getModifier('autoEatHPLimit').toInt();
  int get autoEatThreshold => getModifier('autoEatThreshold').toInt();
  int get autoEquipFoodUnlocked => getModifier('autoEquipFoodUnlocked').toInt();
  int get autoLooting => getModifier('autoLooting').toInt();
  int get autoSlayerUnlocked => getModifier('autoSlayerUnlocked').toInt();
  int get autoSwapFoodUnlocked => getModifier('autoSwapFoodUnlocked').toInt();
  int get bankSpace => getModifier('bankSpace').toInt();
  int basePrimaryProductQuantity({
    required MelvorId skillId,
    MelvorId? actionId,
  }) => getModifier(
    'basePrimaryProductQuantity',
    skillId: skillId,
    actionId: actionId,
  ).toInt();
  int get bleedLifesteal => getModifier('bleedLifesteal').toInt();
  int get bonusCoalMining => getModifier('bonusCoalMining').toInt();
  int get bonusCoalOnDungeonCompletion =>
      getModifier('bonusCoalOnDungeonCompletion').toInt();
  int bonusFishingSpecialChance({MelvorId? actionId}) =>
      getModifier('bonusFishingSpecialChance', actionId: actionId).toInt();
  int get burnLifesteal => getModifier('burnLifesteal').toInt();
  int get bypassSlayerItems => getModifier('bypassSlayerItems').toInt();
  int cannotFishJunk({MelvorId? actionId}) =>
      getModifier('cannotFishJunk', actionId: actionId).toInt();
  int get cantAttack => getModifier('cantAttack').toInt();
  int get cantEvade => getModifier('cantEvade').toInt();
  int get cantRegenBarrier => getModifier('cantRegenBarrier').toInt();
  int get cartographyMapUpgradeInterval =>
      getModifier('cartographyMapUpgradeInterval').toInt();
  int get cartographyPaperMakingInterval =>
      getModifier('cartographyPaperMakingInterval').toInt();
  int get cartographySurveyInterval =>
      getModifier('cartographySurveyInterval').toInt();
  int get combatLootDoublingChance =>
      getModifier('combatLootDoublingChance').toInt();
  int get compostPreservationChance =>
      getModifier('compostPreservationChance').toInt();
  int get convertBoneDropsIntoCake =>
      getModifier('convertBoneDropsIntoCake').toInt();
  int get cookingSuccessCap => getModifier('cookingSuccessCap').toInt();
  int currencyGain({MelvorId? skillId, MelvorId? actionId}) =>
      getModifier('currencyGain', skillId: skillId, actionId: actionId).toInt();
  int get currencyGainFromCombat =>
      getModifier('currencyGainFromCombat').toInt();
  int get currencyGainFromLifesteal =>
      getModifier('currencyGainFromLifesteal').toInt();
  int get currencyGainFromLogSales =>
      getModifier('currencyGainFromLogSales').toInt();
  int get currencyGainFromMonsterDrops =>
      getModifier('currencyGainFromMonsterDrops').toInt();
  int get currencyGainFromSlayerTaskMonsterDrops =>
      getModifier('currencyGainFromSlayerTaskMonsterDrops').toInt();
  int get currencyGainOnMonsterKillBasedOnEvasion =>
      getModifier('currencyGainOnMonsterKillBasedOnEvasion').toInt();
  int get currencyGainOnRegenBasedOnHPGained =>
      getModifier('currencyGainOnRegenBasedOnHPGained').toInt();
  int get currencyGainPerDamageDealtBasedOnCurrencyAmount =>
      getModifier('currencyGainPerDamageDealtBasedOnCurrencyAmount').toInt();
  int get currencyGainPerMagicDamageDealt =>
      getModifier('currencyGainPerMagicDamageDealt').toInt();
  int get currencyGainPerMagicDamageDealtOnSlayerTask =>
      getModifier('currencyGainPerMagicDamageDealtOnSlayerTask').toInt();
  int get currencyGainPerMeleeDamageDealt =>
      getModifier('currencyGainPerMeleeDamageDealt').toInt();
  int get currencyGainPerRangedDamageDealt =>
      getModifier('currencyGainPerRangedDamageDealt').toInt();
  double get currentHPDamageTakenOnAttack =>
      getModifier('currentHPDamageTakenOnAttack').toDouble();
  int get damageDealt => getModifier('damageDealt').toInt();
  int get damageDealtToAllMonsters =>
      getModifier('damageDealtToAllMonsters').toInt();
  int get damageDealtToBosses => getModifier('damageDealtToBosses').toInt();
  int damageDealtToMonstersInArea({required MelvorId categoryId}) =>
      getModifier(
        'damageDealtToMonstersInArea',
        categoryId: categoryId,
      ).toInt();
  int get damageDealtToSlayerTasks =>
      getModifier('damageDealtToSlayerTasks').toInt();
  int get damageTaken => getModifier('damageTaken').toInt();
  int get disableAttackDamage => getModifier('disableAttackDamage').toInt();
  int doubleItemsSkill({
    required MelvorId skillId,
    MelvorId? actionId,
    MelvorId? categoryId,
  }) => getModifier(
    'doubleItemsSkill',
    skillId: skillId,
    actionId: actionId,
    categoryId: categoryId,
  ).toInt();
  int get doubleRuneProvision => getModifier('doubleRuneProvision').toInt();
  int get dragonBreathDamage => getModifier('dragonBreathDamage').toInt();
  int get dungeonEquipmentSwapping =>
      getModifier('dungeonEquipmentSwapping').toInt();
  int get effectIgnoreChance => getModifier('effectIgnoreChance').toInt();
  int get effectImmunity => getModifier('effectImmunity').toInt();
  int get elementalRuneChance => getModifier('elementalRuneChance').toInt();
  int get elementalRuneQuantity => getModifier('elementalRuneQuantity').toInt();
  int get enableNightfallSeason => getModifier('enableNightfallSeason').toInt();
  int get equipmentAttackSpeed => getModifier('equipmentAttackSpeed').toInt();
  int get equipmentSets => getModifier('equipmentSets').toInt();
  int get evasion => getModifier('evasion').toInt();
  int farmingCropsCannotDie({MelvorId? actionId}) =>
      getModifier('farmingCropsCannotDie', actionId: actionId).toInt();
  double farmingSeedReturn({required MelvorId actionId}) =>
      getModifier('farmingSeedReturn', actionId: actionId).toDouble();
  int get firemakingBonfireInterval =>
      getModifier('firemakingBonfireInterval').toInt();
  int get firemakingLogCurrencyGain =>
      getModifier('firemakingLogCurrencyGain').toInt();
  int get fishingAdditionalSpecialItemChance =>
      getModifier('fishingAdditionalSpecialItemChance').toInt();
  int get fishingCookedChance => getModifier('fishingCookedChance').toInt();
  double fishingMasteryDoublingChance({required MelvorId actionId}) =>
      getModifier(
        'fishingMasteryDoublingChance',
        actionId: actionId,
      ).toDouble();
  int get fishingSpecialChance => getModifier('fishingSpecialChance').toInt();
  int flatAdditionalPrimaryProductQuantity({required MelvorId skillId}) =>
      getModifier(
        'flatAdditionalPrimaryProductQuantity',
        skillId: skillId,
      ).toInt();
  int flatAdditionalSkillItem({
    required MelvorId skillId,
    required MelvorId itemId,
    MelvorId? actionId,
  }) => getModifier(
    'flatAdditionalSkillItem',
    skillId: skillId,
    actionId: actionId,
    itemId: itemId,
  ).toInt();
  int get flatAttackInterval => getModifier('flatAttackInterval').toInt();
  double flatBasePrimaryProductQuantity({
    required MelvorId skillId,
    MelvorId? actionId,
    MelvorId? categoryId,
  }) => getModifier(
    'flatBasePrimaryProductQuantity',
    skillId: skillId,
    actionId: actionId,
    categoryId: categoryId,
  ).toDouble();
  int flatBasePrimaryProductQuantityChance({required MelvorId skillId}) =>
      getModifier(
        'flatBasePrimaryProductQuantityChance',
        skillId: skillId,
      ).toInt();
  int flatBaseRandomProductQuantity({
    required MelvorId skillId,
    required MelvorId itemId,
  }) => getModifier(
    'flatBaseRandomProductQuantity',
    skillId: skillId,
    itemId: itemId,
  ).toInt();
  int get flatBlockAttackBonus => getModifier('flatBlockAttackBonus').toInt();
  int get flatCoalGainedOnCookingFailure =>
      getModifier('flatCoalGainedOnCookingFailure').toInt();
  int get flatCraftingDragonhideCost =>
      getModifier('flatCraftingDragonhideCost').toInt();
  int get flatCurrencyGainFromMonsterDrops =>
      getModifier('flatCurrencyGainFromMonsterDrops').toInt();
  int get flatCurrencyGainOnEnemyHit =>
      getModifier('flatCurrencyGainOnEnemyHit').toInt();
  int get flatCurrencyGainWhenHitBasedOnResistance =>
      getModifier('flatCurrencyGainWhenHitBasedOnResistance').toInt();
  int flatFarmingSeedCost({required MelvorId categoryId}) =>
      getModifier('flatFarmingSeedCost', categoryId: categoryId).toInt();
  double get flatHPRegen => getModifier('flatHPRegen').toDouble();
  int get flatHPRegenBasedOnMagicMaxHit =>
      getModifier('flatHPRegenBasedOnMagicMaxHit').toInt();
  int get flatHPRegenBasedOnMeleeMaxHit =>
      getModifier('flatHPRegenBasedOnMeleeMaxHit').toInt();
  int get flatHPRegenBasedOnRangedMaxHit =>
      getModifier('flatHPRegenBasedOnRangedMaxHit').toInt();
  int flatHiddenSkillLevel({required MelvorId skillId}) =>
      getModifier('flatHiddenSkillLevel', skillId: skillId).toInt();
  int get flatMagicAttackBonus => getModifier('flatMagicAttackBonus').toInt();
  int get flatMagicDefenceBonus => getModifier('flatMagicDefenceBonus').toInt();
  int get flatMagicMaxHit => getModifier('flatMagicMaxHit').toInt();
  double get flatMagicMinHit => getModifier('flatMagicMinHit').toDouble();
  int get flatMasteryTokens => getModifier('flatMasteryTokens').toInt();
  double get flatMaxHit => getModifier('flatMaxHit').toDouble();
  int get flatMaxHitpoints => getModifier('flatMaxHitpoints').toInt();
  int get flatMeleeDefenceBonus => getModifier('flatMeleeDefenceBonus').toInt();
  int get flatMeleeDefenceBonusBasedOnResistance =>
      getModifier('flatMeleeDefenceBonusBasedOnResistance').toInt();
  int get flatMeleeStrengthBonus =>
      getModifier('flatMeleeStrengthBonus').toInt();
  int get flatMinHit => getModifier('flatMinHit').toInt();
  int flatMiningNodeHP({MelvorId? actionId}) =>
      getModifier('flatMiningNodeHP', actionId: actionId).toInt();
  int get flatMonsterRespawnInterval =>
      getModifier('flatMonsterRespawnInterval').toInt();
  int get flatPotionCharges => getModifier('flatPotionCharges').toInt();
  int get flatPrayerPointCost => getModifier('flatPrayerPointCost').toInt();
  int get flatRangedAttackBonus => getModifier('flatRangedAttackBonus').toInt();
  int get flatRangedDefenceBonus =>
      getModifier('flatRangedDefenceBonus').toInt();
  int get flatRangedDefenceBonusBasedOnResistance =>
      getModifier('flatRangedDefenceBonusBasedOnResistance').toInt();
  int get flatRangedStrengthBonus =>
      getModifier('flatRangedStrengthBonus').toInt();
  int get flatReflectDamage => getModifier('flatReflectDamage').toInt();
  int get flatRegenerationInterval =>
      getModifier('flatRegenerationInterval').toInt();
  int get flatResistance => getModifier('flatResistance').toInt();
  int get flatResistanceAgainstMagic =>
      getModifier('flatResistanceAgainstMagic').toInt();
  int get flatResistanceAgainstMelee =>
      getModifier('flatResistanceAgainstMelee').toInt();
  int get flatResistanceAgainstRanged =>
      getModifier('flatResistanceAgainstRanged').toInt();
  int get flatResistanceAgainstSlayerTasks =>
      getModifier('flatResistanceAgainstSlayerTasks').toInt();
  int flatSkillInterval({required MelvorId skillId, MelvorId? actionId}) =>
      getModifier(
        'flatSkillInterval',
        skillId: skillId,
        actionId: actionId,
      ).toInt();
  int get flatSlashAttackBonus => getModifier('flatSlashAttackBonus').toInt();
  int get flatSlayerAreaEffectNegation =>
      getModifier('flatSlayerAreaEffectNegation').toInt();
  int get flatSmithingCoalCost => getModifier('flatSmithingCoalCost').toInt();
  int get flatStabAttackBonus => getModifier('flatStabAttackBonus').toInt();
  int flatSummoningShardCost({MelvorId? actionId}) =>
      getModifier('flatSummoningShardCost', actionId: actionId).toInt();
  int get flatThievingCurrencyGain =>
      getModifier('flatThievingCurrencyGain').toInt();
  int get flatTier1SummoningShardCost =>
      getModifier('flatTier1SummoningShardCost').toInt();
  int get flatTier2SummoningShardCost =>
      getModifier('flatTier2SummoningShardCost').toInt();
  int get flatTier3SummoningShardCost =>
      getModifier('flatTier3SummoningShardCost').toInt();
  int get flatTownshipEducation => getModifier('flatTownshipEducation').toInt();
  int get flatTownshipHappiness => getModifier('flatTownshipHappiness').toInt();
  int foodHealingValue({MelvorId? actionId}) =>
      getModifier('foodHealingValue', actionId: actionId).toInt();
  int get foodPreservationChance =>
      getModifier('foodPreservationChance').toInt();
  int get freeBonfires => getModifier('freeBonfires').toInt();
  int get freeProtectItem => getModifier('freeProtectItem').toInt();
  int get giveRandomComboRunesRunecrafting =>
      getModifier('giveRandomComboRunesRunecrafting').toInt();
  double get globalEvasionHPScaling =>
      getModifier('globalEvasionHPScaling').toDouble();
  int get globalItemDoublingChance =>
      getModifier('globalItemDoublingChance').toInt();
  int get golbinRaidMaximumAmmo => getModifier('golbinRaidMaximumAmmo').toInt();
  int get golbinRaidMaximumRunes =>
      getModifier('golbinRaidMaximumRunes').toInt();
  int get golbinRaidMinimumFood => getModifier('golbinRaidMinimumFood').toInt();
  int get golbinRaidPassiveSlotUnlocked =>
      getModifier('golbinRaidPassiveSlotUnlocked').toInt();
  int get golbinRaidPrayerLevel => getModifier('golbinRaidPrayerLevel').toInt();
  int get golbinRaidPrayerPointsPerWave =>
      getModifier('golbinRaidPrayerPointsPerWave').toInt();
  int get golbinRaidPrayerUnlocked =>
      getModifier('golbinRaidPrayerUnlocked').toInt();
  int get golbinRaidStartingPrayerPoints =>
      getModifier('golbinRaidStartingPrayerPoints').toInt();
  int get golbinRaidStartingRuneCount =>
      getModifier('golbinRaidStartingRuneCount').toInt();
  int get golbinRaidStartingWeapon =>
      getModifier('golbinRaidStartingWeapon').toInt();
  int get golbinRaidWaveSkipCost =>
      getModifier('golbinRaidWaveSkipCost').toInt();
  int halveAgilityObstacleNegatives({required MelvorId actionId}) =>
      getModifier('halveAgilityObstacleNegatives', actionId: actionId).toInt();
  int get halveWoodcuttingDoubleChance =>
      getModifier('halveWoodcuttingDoubleChance').toInt();
  int get healingOnAttackBasedOnResistance =>
      getModifier('healingOnAttackBasedOnResistance').toInt();
  double get hitpointRegeneration =>
      getModifier('hitpointRegeneration').toDouble();
  int get hitpointRegenerationAgainstSlayerTasks =>
      getModifier('hitpointRegenerationAgainstSlayerTasks').toInt();
  int get hpRegenWhenEnemyHasMoreEvasion =>
      getModifier('hpRegenWhenEnemyHasMoreEvasion').toInt();
  int ignoreThievingDamage({required MelvorId actionId}) =>
      getModifier('ignoreThievingDamage', actionId: actionId).toInt();
  int get itemProtection => getModifier('itemProtection').toInt();
  int get lifesteal => getModifier('lifesteal').toInt();
  int get magicAccuracyRating => getModifier('magicAccuracyRating').toInt();
  int get magicCritChance => getModifier('magicCritChance').toInt();
  int get magicDamageBonus => getModifier('magicDamageBonus').toInt();
  int get magicEvasion => getModifier('magicEvasion').toInt();
  int get magicImmunity => getModifier('magicImmunity').toInt();
  int get magicLifesteal => getModifier('magicLifesteal').toInt();
  int get magicMaxHit => getModifier('magicMaxHit').toInt();
  int get magicMinHitBasedOnMaxHit =>
      getModifier('magicMinHitBasedOnMaxHit').toInt();
  int get magicMinHitBasedOnMaxHitSlayerTask =>
      getModifier('magicMinHitBasedOnMaxHitSlayerTask').toInt();
  int get magicProtection => getModifier('magicProtection').toInt();
  int get masteryPoolCap => getModifier('masteryPoolCap').toInt();
  double masteryXP({MelvorId? skillId}) =>
      getModifier('masteryXP', skillId: skillId).toDouble();
  int get maxCurrencyMultiplierPerDamage =>
      getModifier('maxCurrencyMultiplierPerDamage').toInt();
  int get maxHit => getModifier('maxHit').toInt();
  int get maxHitpoints => getModifier('maxHitpoints').toInt();
  int get meleeAccuracyRating => getModifier('meleeAccuracyRating').toInt();
  int get meleeCritChance => getModifier('meleeCritChance').toInt();
  int get meleeEvasion => getModifier('meleeEvasion').toInt();
  int get meleeImmunity => getModifier('meleeImmunity').toInt();
  int get meleeLifesteal => getModifier('meleeLifesteal').toInt();
  int get meleeMaxHit => getModifier('meleeMaxHit').toInt();
  int get meleeMinHitBasedOnMaxHitSlayerTask =>
      getModifier('meleeMinHitBasedOnMaxHitSlayerTask').toInt();
  int get meleeProtection => getModifier('meleeProtection').toInt();
  int get meleeStrengthBonus => getModifier('meleeStrengthBonus').toInt();
  int get meteoriteLocationChance =>
      getModifier('meteoriteLocationChance').toInt();
  int get minCurrencyMultiplierPerDamage =>
      getModifier('minCurrencyMultiplierPerDamage').toInt();
  int get minHitBasedOnMaxHit => getModifier('minHitBasedOnMaxHit').toInt();
  int get minThievingCurrencyGain =>
      getModifier('minThievingCurrencyGain').toInt();
  int get miningBarChance => getModifier('miningBarChance').toInt();
  int get miningGemChance => getModifier('miningGemChance').toInt();
  int get miningNodeRespawnInterval =>
      getModifier('miningNodeRespawnInterval').toInt();
  int noMiningNodeDamageChance({required MelvorId categoryId}) =>
      getModifier('noMiningNodeDamageChance', categoryId: categoryId).toInt();
  int get nonCombatSkillXP => getModifier('nonCombatSkillXP').toInt();
  int nonShardSummoningCostReduction({required MelvorId actionId}) =>
      getModifier('nonShardSummoningCostReduction', actionId: actionId).toInt();
  int get offItemChance => getModifier('offItemChance').toInt();
  int get onHitSlowMagnitude => getModifier('onHitSlowMagnitude').toInt();
  int get otherStyleImmunity => getModifier('otherStyleImmunity').toInt();
  int perfectCookChance({MelvorId? actionId, MelvorId? categoryId}) =>
      getModifier(
        'perfectCookChance',
        actionId: actionId,
        categoryId: categoryId,
      ).toInt();
  int get poisonLifesteal => getModifier('poisonLifesteal').toInt();
  int get potionChargePreservationChance =>
      getModifier('potionChargePreservationChance').toInt();
  int potionCharges({required MelvorId actionId}) =>
      getModifier('potionCharges', actionId: actionId).toInt();
  int get prayerPointCost => getModifier('prayerPointCost').toInt();
  int get prayerPointPreservationChance =>
      getModifier('prayerPointPreservationChance').toInt();
  int get randomHerblorePotionChance =>
      getModifier('randomHerblorePotionChance').toInt();
  double randomProductChance({
    required MelvorId skillId,
    required MelvorId itemId,
  }) => getModifier(
    'randomProductChance',
    skillId: skillId,
    itemId: itemId,
  ).toDouble();
  int get rangedAccuracyRating => getModifier('rangedAccuracyRating').toInt();
  int get rangedCritChance => getModifier('rangedCritChance').toInt();
  int get rangedEvasion => getModifier('rangedEvasion').toInt();
  int get rangedImmunity => getModifier('rangedImmunity').toInt();
  int get rangedLifesteal => getModifier('rangedLifesteal').toInt();
  int get rangedMaxHit => getModifier('rangedMaxHit').toInt();
  int get rangedMinHitBasedOnMaxHitSlayerTask =>
      getModifier('rangedMinHitBasedOnMaxHitSlayerTask').toInt();
  int get rangedProtection => getModifier('rangedProtection').toInt();
  int get rangedStrengthBonus => getModifier('rangedStrengthBonus').toInt();
  int get rebirthChance => getModifier('rebirthChance').toInt();
  int get reflectDamage => getModifier('reflectDamage').toInt();
  int get resistance => getModifier('resistance').toInt();
  int get rolledReflectDamage => getModifier('rolledReflectDamage').toInt();
  int get runePreservationChance =>
      getModifier('runePreservationChance').toInt();
  int get runecraftingBaseXPForRunes =>
      getModifier('runecraftingBaseXPForRunes').toInt();
  int runecraftingRuneCostReduction({required MelvorId actionId}) =>
      getModifier('runecraftingRuneCostReduction', actionId: actionId).toInt();
  int get seedDropConversionChance =>
      getModifier('seedDropConversionChance').toInt();
  double skillInterval({required MelvorId skillId, MelvorId? actionId}) =>
      getModifier(
        'skillInterval',
        skillId: skillId,
        actionId: actionId,
      ).toDouble();
  int skillItemDoublingChance({
    required MelvorId skillId,
    MelvorId? actionId,
    MelvorId? categoryId,
  }) => getModifier(
    'skillItemDoublingChance',
    skillId: skillId,
    actionId: actionId,
    categoryId: categoryId,
  ).toInt();
  int skillPreservationCap({required MelvorId skillId}) =>
      getModifier('skillPreservationCap', skillId: skillId).toInt();
  double skillPreservationChance({
    MelvorId? skillId,
    MelvorId? actionId,
    MelvorId? categoryId,
  }) => getModifier(
    'skillPreservationChance',
    skillId: skillId,
    actionId: actionId,
    categoryId: categoryId,
  ).toDouble();
  int skillXP({MelvorId? skillId}) =>
      getModifier('skillXP', skillId: skillId).toInt();
  int get slayerTaskLength => getModifier('slayerTaskLength').toInt();
  int get smithingCoalCost => getModifier('smithingCoalCost').toInt();
  int get strongholdEquipmentSwapping =>
      getModifier('strongholdEquipmentSwapping').toInt();
  int get stunDurationIncreaseChance =>
      getModifier('stunDurationIncreaseChance').toInt();
  double successfulCookChance({MelvorId? actionId}) =>
      getModifier('successfulCookChance', actionId: actionId).toDouble();
  int get summoningAttackInterval =>
      getModifier('summoningAttackInterval').toInt();
  int get summoningAttackLifesteal =>
      getModifier('summoningAttackLifesteal').toInt();
  int get summoningChargePreservationChance =>
      getModifier('summoningChargePreservationChance').toInt();
  int get summoningMaxHit => getModifier('summoningMaxHit').toInt();
  int get summoningSynergy45 => getModifier('summoningSynergy_4_5').toInt();
  int get summoningSynergyEntLeprechaun =>
      getModifier('summoningSynergy_Ent_Leprechaun').toInt();
  int get summoningSynergyLeprechaunDevil =>
      getModifier('summoningSynergy_Leprechaun_Devil').toInt();
  int get summoningSynergyOctopusLeprechaun =>
      getModifier('summoningSynergy_Octopus_Leprechaun').toInt();
  int get thievingAreaUniqueChancePercent =>
      getModifier('thievingAreaUniqueChancePercent').toInt();
  int get thievingAutoSellPrice => getModifier('thievingAutoSellPrice').toInt();
  int get thievingFarmerHerbSackChance =>
      getModifier('thievingFarmerHerbSackChance').toInt();
  int get thievingMinerRandomBarChance =>
      getModifier('thievingMinerRandomBarChance').toInt();
  int thievingStealth({MelvorId? actionId}) =>
      getModifier('thievingStealth', actionId: actionId).toInt();
  int get townshipBuildingCost => getModifier('townshipBuildingCost').toInt();
  int townshipBuildingProduction({required MelvorId categoryId}) =>
      getModifier('townshipBuildingProduction', categoryId: categoryId).toInt();
  int get townshipGPProduction => getModifier('townshipGPProduction').toInt();
  int get townshipMaxStorage => getModifier('townshipMaxStorage').toInt();
  double get townshipRepairCost => getModifier('townshipRepairCost').toDouble();
  int townshipResourceProduction({MelvorId? actionId}) =>
      getModifier('townshipResourceProduction', actionId: actionId).toInt();
  int get townshipTaxPerCitizen => getModifier('townshipTaxPerCitizen').toInt();
  double get townshipTraderCost => getModifier('townshipTraderCost').toDouble();
  int get treeCutLimit => getModifier('treeCutLimit').toInt();
  int get woodcuttingJewelryChance =>
      getModifier('woodcuttingJewelryChance').toInt();
  int get woodcuttingXPAddedAsFiremakingXP =>
      getModifier('woodcuttingXPAddedAsFiremakingXP').toInt();
}
