// GENERATED FILE - DO NOT EDIT
//
// Generated by: dart run tool/generate_modifier_names.dart
//
// This file contains constants for all modifier names found in the
// Melvor Idle JSON data files.

// ignore_for_file: constant_identifier_names

/// Constants for modifier names used in the game data.
///
/// These match the keys found in "modifiers" objects in the JSON.
abstract final class ModifierNames {
  static const String accuracyRating = 'accuracyRating';
  static const String additionalItemBasedOnPrimaryQuantityChance =
      'additionalItemBasedOnPrimaryQuantityChance';
  static const String additionalPrimaryProductChance =
      'additionalPrimaryProductChance';
  static const String additionalRandomGemChance = 'additionalRandomGemChance';
  static const String additionalRandomSkillItemChance =
      'additionalRandomSkillItemChance';
  static const String agilityItemCostReductionCanReach100 =
      'agilityItemCostReductionCanReach100';
  static const String agilityObstacleCost = 'agilityObstacleCost';
  static const String agilityObstacleItemCost = 'agilityObstacleItemCost';
  static const String allowAttackAugmentingMagic = 'allowAttackAugmentingMagic';
  static const String allowLootContainerStacking = 'allowLootContainerStacking';
  static const String allowSignetDrops = 'allowSignetDrops';
  static const String altMagicRunePreservationChance =
      'altMagicRunePreservationChance';
  static const String altMagicSkillXP = 'altMagicSkillXP';
  static const String ammoPreservationChance = 'ammoPreservationChance';
  static const String attackInterval = 'attackInterval';
  static const String attackRolls = 'attackRolls';
  static const String autoBurying = 'autoBurying';
  static const String autoEatEfficiency = 'autoEatEfficiency';
  static const String autoEatHPLimit = 'autoEatHPLimit';
  static const String autoEatThreshold = 'autoEatThreshold';
  static const String autoEquipFoodUnlocked = 'autoEquipFoodUnlocked';
  static const String autoLooting = 'autoLooting';
  static const String autoSlayerUnlocked = 'autoSlayerUnlocked';
  static const String autoSwapFoodUnlocked = 'autoSwapFoodUnlocked';
  static const String bankSpace = 'bankSpace';
  static const String basePrimaryProductQuantity = 'basePrimaryProductQuantity';
  static const String bleedLifesteal = 'bleedLifesteal';
  static const String bonusCoalMining = 'bonusCoalMining';
  static const String bonusCoalOnDungeonCompletion =
      'bonusCoalOnDungeonCompletion';
  static const String bonusFishingSpecialChance = 'bonusFishingSpecialChance';
  static const String burnLifesteal = 'burnLifesteal';
  static const String bypassSlayerItems = 'bypassSlayerItems';
  static const String cannotFishJunk = 'cannotFishJunk';
  static const String cantAttack = 'cantAttack';
  static const String cantEvade = 'cantEvade';
  static const String cantRegenBarrier = 'cantRegenBarrier';
  static const String cartographyMapUpgradeInterval =
      'cartographyMapUpgradeInterval';
  static const String cartographyPaperMakingInterval =
      'cartographyPaperMakingInterval';
  static const String cartographySurveyInterval = 'cartographySurveyInterval';
  static const String combatLootDoublingChance = 'combatLootDoublingChance';
  static const String compostPreservationChance = 'compostPreservationChance';
  static const String convertBoneDropsIntoCake = 'convertBoneDropsIntoCake';
  static const String cookingSuccessCap = 'cookingSuccessCap';
  static const String currencyGain = 'currencyGain';
  static const String currencyGainFromCombat = 'currencyGainFromCombat';
  static const String currencyGainFromLifesteal = 'currencyGainFromLifesteal';
  static const String currencyGainFromLogSales = 'currencyGainFromLogSales';
  static const String currencyGainFromMonsterDrops =
      'currencyGainFromMonsterDrops';
  static const String currencyGainFromSlayerTaskMonsterDrops =
      'currencyGainFromSlayerTaskMonsterDrops';
  static const String currencyGainOnMonsterKillBasedOnEvasion =
      'currencyGainOnMonsterKillBasedOnEvasion';
  static const String currencyGainOnRegenBasedOnHPGained =
      'currencyGainOnRegenBasedOnHPGained';
  static const String currencyGainPerDamageDealtBasedOnCurrencyAmount =
      'currencyGainPerDamageDealtBasedOnCurrencyAmount';
  static const String currencyGainPerMagicDamageDealt =
      'currencyGainPerMagicDamageDealt';
  static const String currencyGainPerMagicDamageDealtOnSlayerTask =
      'currencyGainPerMagicDamageDealtOnSlayerTask';
  static const String currencyGainPerMeleeDamageDealt =
      'currencyGainPerMeleeDamageDealt';
  static const String currencyGainPerRangedDamageDealt =
      'currencyGainPerRangedDamageDealt';
  static const String currentHPDamageTakenOnAttack =
      'currentHPDamageTakenOnAttack';
  static const String damageDealt = 'damageDealt';
  static const String damageDealtToAllMonsters = 'damageDealtToAllMonsters';
  static const String damageDealtToBosses = 'damageDealtToBosses';
  static const String damageDealtToMonstersInArea =
      'damageDealtToMonstersInArea';
  static const String damageDealtToSlayerTasks = 'damageDealtToSlayerTasks';
  static const String damageTaken = 'damageTaken';
  static const String disableAttackDamage = 'disableAttackDamage';
  static const String doubleItemsSkill = 'doubleItemsSkill';
  static const String doubleRuneProvision = 'doubleRuneProvision';
  static const String dragonBreathDamage = 'dragonBreathDamage';
  static const String dungeonEquipmentSwapping = 'dungeonEquipmentSwapping';
  static const String effectIgnoreChance = 'effectIgnoreChance';
  static const String effectImmunity = 'effectImmunity';
  static const String elementalRuneChance = 'elementalRuneChance';
  static const String elementalRuneQuantity = 'elementalRuneQuantity';
  static const String enableNightfallSeason = 'enableNightfallSeason';
  static const String equipmentSets = 'equipmentSets';
  static const String evasion = 'evasion';
  static const String farmingCropsCannotDie = 'farmingCropsCannotDie';
  static const String farmingSeedReturn = 'farmingSeedReturn';
  static const String firemakingBonfireInterval = 'firemakingBonfireInterval';
  static const String firemakingLogCurrencyGain = 'firemakingLogCurrencyGain';
  static const String fishingAdditionalSpecialItemChance =
      'fishingAdditionalSpecialItemChance';
  static const String fishingCookedChance = 'fishingCookedChance';
  static const String fishingMasteryDoublingChance =
      'fishingMasteryDoublingChance';
  static const String fishingSpecialChance = 'fishingSpecialChance';
  static const String flatAdditionalPrimaryProductQuantity =
      'flatAdditionalPrimaryProductQuantity';
  static const String flatAdditionalSkillItem = 'flatAdditionalSkillItem';
  static const String flatAttackInterval = 'flatAttackInterval';
  static const String flatBasePrimaryProductQuantity =
      'flatBasePrimaryProductQuantity';
  static const String flatBasePrimaryProductQuantityChance =
      'flatBasePrimaryProductQuantityChance';
  static const String flatBaseRandomProductQuantity =
      'flatBaseRandomProductQuantity';
  static const String flatBlockAttackBonus = 'flatBlockAttackBonus';
  static const String flatCoalGainedOnCookingFailure =
      'flatCoalGainedOnCookingFailure';
  static const String flatCraftingDragonhideCost = 'flatCraftingDragonhideCost';
  static const String flatCurrencyGainFromMonsterDrops =
      'flatCurrencyGainFromMonsterDrops';
  static const String flatCurrencyGainOnEnemyHit = 'flatCurrencyGainOnEnemyHit';
  static const String flatCurrencyGainWhenHitBasedOnResistance =
      'flatCurrencyGainWhenHitBasedOnResistance';
  static const String flatFarmingSeedCost = 'flatFarmingSeedCost';
  static const String flatHPRegen = 'flatHPRegen';
  static const String flatHPRegenBasedOnMagicMaxHit =
      'flatHPRegenBasedOnMagicMaxHit';
  static const String flatHPRegenBasedOnMeleeMaxHit =
      'flatHPRegenBasedOnMeleeMaxHit';
  static const String flatHPRegenBasedOnRangedMaxHit =
      'flatHPRegenBasedOnRangedMaxHit';
  static const String flatHiddenSkillLevel = 'flatHiddenSkillLevel';
  static const String flatMagicDefenceBonus = 'flatMagicDefenceBonus';
  static const String flatMagicMaxHit = 'flatMagicMaxHit';
  static const String flatMagicMinHit = 'flatMagicMinHit';
  static const String flatMasteryTokens = 'flatMasteryTokens';
  static const String flatMaxHit = 'flatMaxHit';
  static const String flatMaxHitpoints = 'flatMaxHitpoints';
  static const String flatMeleeDefenceBonus = 'flatMeleeDefenceBonus';
  static const String flatMeleeDefenceBonusBasedOnResistance =
      'flatMeleeDefenceBonusBasedOnResistance';
  static const String flatMeleeStrengthBonus = 'flatMeleeStrengthBonus';
  static const String flatMinHit = 'flatMinHit';
  static const String flatMiningNodeHP = 'flatMiningNodeHP';
  static const String flatMonsterRespawnInterval = 'flatMonsterRespawnInterval';
  static const String flatPotionCharges = 'flatPotionCharges';
  static const String flatPrayerPointCost = 'flatPrayerPointCost';
  static const String flatRangedAttackBonus = 'flatRangedAttackBonus';
  static const String flatRangedDefenceBonus = 'flatRangedDefenceBonus';
  static const String flatRangedDefenceBonusBasedOnResistance =
      'flatRangedDefenceBonusBasedOnResistance';
  static const String flatRangedStrengthBonus = 'flatRangedStrengthBonus';
  static const String flatReflectDamage = 'flatReflectDamage';
  static const String flatRegenerationInterval = 'flatRegenerationInterval';
  static const String flatResistance = 'flatResistance';
  static const String flatResistanceAgainstMagic = 'flatResistanceAgainstMagic';
  static const String flatResistanceAgainstMelee = 'flatResistanceAgainstMelee';
  static const String flatResistanceAgainstRanged =
      'flatResistanceAgainstRanged';
  static const String flatResistanceAgainstSlayerTasks =
      'flatResistanceAgainstSlayerTasks';
  static const String flatSkillInterval = 'flatSkillInterval';
  static const String flatSlashAttackBonus = 'flatSlashAttackBonus';
  static const String flatSlayerAreaEffectNegation =
      'flatSlayerAreaEffectNegation';
  static const String flatSmithingCoalCost = 'flatSmithingCoalCost';
  static const String flatStabAttackBonus = 'flatStabAttackBonus';
  static const String flatSummoningShardCost = 'flatSummoningShardCost';
  static const String flatThievingCurrencyGain = 'flatThievingCurrencyGain';
  static const String flatTier1SummoningShardCost =
      'flatTier1SummoningShardCost';
  static const String flatTier2SummoningShardCost =
      'flatTier2SummoningShardCost';
  static const String flatTier3SummoningShardCost =
      'flatTier3SummoningShardCost';
  static const String flatTownshipEducation = 'flatTownshipEducation';
  static const String flatTownshipHappiness = 'flatTownshipHappiness';
  static const String foodHealingValue = 'foodHealingValue';
  static const String foodPreservationChance = 'foodPreservationChance';
  static const String freeBonfires = 'freeBonfires';
  static const String freeProtectItem = 'freeProtectItem';
  static const String giveRandomComboRunesRunecrafting =
      'giveRandomComboRunesRunecrafting';
  static const String globalEvasionHPScaling = 'globalEvasionHPScaling';
  static const String globalItemDoublingChance = 'globalItemDoublingChance';
  static const String golbinRaidMaximumAmmo = 'golbinRaidMaximumAmmo';
  static const String golbinRaidMaximumRunes = 'golbinRaidMaximumRunes';
  static const String golbinRaidMinimumFood = 'golbinRaidMinimumFood';
  static const String golbinRaidPassiveSlotUnlocked =
      'golbinRaidPassiveSlotUnlocked';
  static const String golbinRaidPrayerLevel = 'golbinRaidPrayerLevel';
  static const String golbinRaidPrayerPointsPerWave =
      'golbinRaidPrayerPointsPerWave';
  static const String golbinRaidPrayerUnlocked = 'golbinRaidPrayerUnlocked';
  static const String golbinRaidStartingPrayerPoints =
      'golbinRaidStartingPrayerPoints';
  static const String golbinRaidStartingRuneCount =
      'golbinRaidStartingRuneCount';
  static const String golbinRaidStartingWeapon = 'golbinRaidStartingWeapon';
  static const String golbinRaidWaveSkipCost = 'golbinRaidWaveSkipCost';
  static const String halveAgilityObstacleNegatives =
      'halveAgilityObstacleNegatives';
  static const String halveWoodcuttingDoubleChance =
      'halveWoodcuttingDoubleChance';
  static const String healingOnAttackBasedOnResistance =
      'healingOnAttackBasedOnResistance';
  static const String hitpointRegeneration = 'hitpointRegeneration';
  static const String hitpointRegenerationAgainstSlayerTasks =
      'hitpointRegenerationAgainstSlayerTasks';
  static const String hpRegenWhenEnemyHasMoreEvasion =
      'hpRegenWhenEnemyHasMoreEvasion';
  static const String ignoreThievingDamage = 'ignoreThievingDamage';
  static const String itemProtection = 'itemProtection';
  static const String lifesteal = 'lifesteal';
  static const String magicAccuracyRating = 'magicAccuracyRating';
  static const String magicCritChance = 'magicCritChance';
  static const String magicDamageBonus = 'magicDamageBonus';
  static const String magicEvasion = 'magicEvasion';
  static const String magicImmunity = 'magicImmunity';
  static const String magicLifesteal = 'magicLifesteal';
  static const String magicMaxHit = 'magicMaxHit';
  static const String magicMinHitBasedOnMaxHit = 'magicMinHitBasedOnMaxHit';
  static const String magicMinHitBasedOnMaxHitSlayerTask =
      'magicMinHitBasedOnMaxHitSlayerTask';
  static const String magicProtection = 'magicProtection';
  static const String masteryPoolCap = 'masteryPoolCap';
  static const String masteryXP = 'masteryXP';
  static const String maxCurrencyMultiplierPerDamage =
      'maxCurrencyMultiplierPerDamage';
  static const String maxHit = 'maxHit';
  static const String maxHitpoints = 'maxHitpoints';
  static const String meleeAccuracyRating = 'meleeAccuracyRating';
  static const String meleeCritChance = 'meleeCritChance';
  static const String meleeEvasion = 'meleeEvasion';
  static const String meleeImmunity = 'meleeImmunity';
  static const String meleeLifesteal = 'meleeLifesteal';
  static const String meleeMaxHit = 'meleeMaxHit';
  static const String meleeMinHitBasedOnMaxHitSlayerTask =
      'meleeMinHitBasedOnMaxHitSlayerTask';
  static const String meleeProtection = 'meleeProtection';
  static const String meleeStrengthBonus = 'meleeStrengthBonus';
  static const String meteoriteLocationChance = 'meteoriteLocationChance';
  static const String minCurrencyMultiplierPerDamage =
      'minCurrencyMultiplierPerDamage';
  static const String minHitBasedOnMaxHit = 'minHitBasedOnMaxHit';
  static const String minThievingCurrencyGain = 'minThievingCurrencyGain';
  static const String miningBarChance = 'miningBarChance';
  static const String miningGemChance = 'miningGemChance';
  static const String miningNodeRespawnInterval = 'miningNodeRespawnInterval';
  static const String noMiningNodeDamageChance = 'noMiningNodeDamageChance';
  static const String nonCombatSkillXP = 'nonCombatSkillXP';
  static const String nonShardSummoningCostReduction =
      'nonShardSummoningCostReduction';
  static const String offItemChance = 'offItemChance';
  static const String onHitSlowMagnitude = 'onHitSlowMagnitude';
  static const String otherStyleImmunity = 'otherStyleImmunity';
  static const String perfectCookChance = 'perfectCookChance';
  static const String poisonLifesteal = 'poisonLifesteal';
  static const String potionChargePreservationChance =
      'potionChargePreservationChance';
  static const String potionCharges = 'potionCharges';
  static const String prayerPointCost = 'prayerPointCost';
  static const String prayerPointPreservationChance =
      'prayerPointPreservationChance';
  static const String randomHerblorePotionChance = 'randomHerblorePotionChance';
  static const String randomProductChance = 'randomProductChance';
  static const String rangedAccuracyRating = 'rangedAccuracyRating';
  static const String rangedCritChance = 'rangedCritChance';
  static const String rangedEvasion = 'rangedEvasion';
  static const String rangedImmunity = 'rangedImmunity';
  static const String rangedLifesteal = 'rangedLifesteal';
  static const String rangedMaxHit = 'rangedMaxHit';
  static const String rangedMinHitBasedOnMaxHitSlayerTask =
      'rangedMinHitBasedOnMaxHitSlayerTask';
  static const String rangedProtection = 'rangedProtection';
  static const String rangedStrengthBonus = 'rangedStrengthBonus';
  static const String rebirthChance = 'rebirthChance';
  static const String reflectDamage = 'reflectDamage';
  static const String resistance = 'resistance';
  static const String rolledReflectDamage = 'rolledReflectDamage';
  static const String runePreservationChance = 'runePreservationChance';
  static const String runecraftingBaseXPForRunes = 'runecraftingBaseXPForRunes';
  static const String runecraftingRuneCostReduction =
      'runecraftingRuneCostReduction';
  static const String seedDropConversionChance = 'seedDropConversionChance';
  static const String skillInterval = 'skillInterval';
  static const String skillItemDoublingChance = 'skillItemDoublingChance';
  static const String skillPreservationCap = 'skillPreservationCap';
  static const String skillPreservationChance = 'skillPreservationChance';
  static const String skillXP = 'skillXP';
  static const String slayerTaskLength = 'slayerTaskLength';
  static const String smithingCoalCost = 'smithingCoalCost';
  static const String strongholdEquipmentSwapping =
      'strongholdEquipmentSwapping';
  static const String stunDurationIncreaseChance = 'stunDurationIncreaseChance';
  static const String successfulCookChance = 'successfulCookChance';
  static const String summoningAttackInterval = 'summoningAttackInterval';
  static const String summoningAttackLifesteal = 'summoningAttackLifesteal';
  static const String summoningChargePreservationChance =
      'summoningChargePreservationChance';
  static const String summoningMaxHit = 'summoningMaxHit';
  static const String summoningSynergy_4_5 = 'summoningSynergy_4_5';
  static const String summoningSynergy_Ent_Leprechaun =
      'summoningSynergy_Ent_Leprechaun';
  static const String summoningSynergy_Leprechaun_Devil =
      'summoningSynergy_Leprechaun_Devil';
  static const String summoningSynergy_Octopus_Leprechaun =
      'summoningSynergy_Octopus_Leprechaun';
  static const String thievingAreaUniqueChancePercent =
      'thievingAreaUniqueChancePercent';
  static const String thievingAutoSellPrice = 'thievingAutoSellPrice';
  static const String thievingFarmerHerbSackChance =
      'thievingFarmerHerbSackChance';
  static const String thievingMinerRandomBarChance =
      'thievingMinerRandomBarChance';
  static const String thievingStealth = 'thievingStealth';
  static const String townshipBuildingCost = 'townshipBuildingCost';
  static const String townshipBuildingProduction = 'townshipBuildingProduction';
  static const String townshipGPProduction = 'townshipGPProduction';
  static const String townshipMaxStorage = 'townshipMaxStorage';
  static const String townshipRepairCost = 'townshipRepairCost';
  static const String townshipResourceProduction = 'townshipResourceProduction';
  static const String townshipTaxPerCitizen = 'townshipTaxPerCitizen';
  static const String townshipTraderCost = 'townshipTraderCost';
  static const String treeCutLimit = 'treeCutLimit';
  static const String woodcuttingJewelryChance = 'woodcuttingJewelryChance';
  static const String woodcuttingXPAddedAsFiremakingXP =
      'woodcuttingXPAddedAsFiremakingXP';
}
