// Generates lib/src/types/modifier_names.dart with ModifiersBase class
// that provides typed getters for all modifier names found in the Melvor
// JSON data files.
//
// Run from the logic/ directory:
//   dart run tool/generate_modifier_names.dart
// ignore_for_file: avoid_print
import 'dart:io';

import 'package:logic/src/data/cache.dart';

/// Convert snake_case to CamelCase.
String camelFromSnake(String snake) {
  return snake.splitMapJoin(
    RegExp('_'),
    onMatch: (m) => '',
    onNonMatch: (n) => n.capitalizeFirst(),
  );
}

String lowercaseCamelFromSnake(String snake) =>
    camelFromSnake(snake).lowerFirst();

extension CapitalizeString on String {
  String capitalizeFirst() {
    if (isEmpty) {
      return this;
    }
    return '${this[0].toUpperCase()}${substring(1)}';
  }

  String lowerFirst() {
    if (isEmpty) {
      return this;
    }
    return '${this[0].toLowerCase()}${substring(1)}';
  }
}

void main() async {
  final cache = Cache(cacheDir: defaultCacheDir);

  try {
    print('Loading JSON data files...');
    final demoData = await cache.ensureDemoData();
    final fullData = await cache.ensureFullData();

    // Collect all unique modifier names
    final modifierNames = <String>{};
    collectModifierNames(demoData, modifierNames);
    collectModifierNames(fullData, modifierNames);

    print('Found ${modifierNames.length} unique modifier names.');

    // Generate the Dart file
    final output = generateDartFile(modifierNames);

    // Write to lib/src/types/modifier_names.dart
    final outputFile = File('lib/src/types/modifier_names.dart');
    await outputFile.writeAsString(output);

    // Then run dart format on the file
    await Process.run('dart', ['format', outputFile.path]);

    print('Generated: ${outputFile.path}');
  } finally {
    cache.close();
  }
}

/// Recursively collects all modifier names from a JSON structure.
void collectModifierNames(dynamic json, Set<String> names) {
  if (json is Map<String, dynamic>) {
    // Check for modifiers at this level
    final modifiers = json['modifiers'];
    if (modifiers is Map<String, dynamic>) {
      for (final key in modifiers.keys) {
        // Skip special keys like "add" which contain nested modifiers
        if (key == 'add') {
          if (modifiers[key] is Map<String, dynamic>) {
            collectModifierNamesFromMap(
              modifiers[key] as Map<String, dynamic>,
              names,
            );
          }
        } else {
          names.add(key);
        }
      }
    }

    // Also check enemyModifiers and playerModifiers
    final enemyModifiers = json['enemyModifiers'];
    if (enemyModifiers is Map<String, dynamic>) {
      collectModifierNamesFromMap(enemyModifiers, names);
    }

    final playerModifiers = json['playerModifiers'];
    if (playerModifiers is Map<String, dynamic>) {
      collectModifierNamesFromMap(playerModifiers, names);
    }

    // Recurse into all values
    for (final value in json.values) {
      collectModifierNames(value, names);
    }
  } else if (json is List) {
    for (final item in json) {
      collectModifierNames(item, names);
    }
  }
}

/// Collects modifier names from a modifiers map, handling nested "add" keys.
void collectModifierNamesFromMap(Map<String, dynamic> map, Set<String> names) {
  for (final key in map.keys) {
    if (key == 'add') {
      if (map[key] is Map<String, dynamic>) {
        collectModifierNamesFromMap(map[key] as Map<String, dynamic>, names);
      }
    } else {
      names.add(key);
    }
  }
}

/// Generates the Dart file content with ModifiersBase class.
String generateDartFile(Set<String> names) {
  final sortedNames = names.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED FILE - DO NOT EDIT')
    ..writeln('//')
    ..writeln('// Generated by: dart run tool/generate_modifier_names.dart')
    ..writeln('//')
    ..writeln(
      '// This file contains the ModifiersBase class with typed getters for all',
    )
    ..writeln('// modifier names found in the Melvor Idle JSON data files.')
    ..writeln()
    ..writeln("import 'package:meta/meta.dart';")
    ..writeln()
    ..writeln('/// Base class providing typed access to modifier values.')
    ..writeln('///')
    ..writeln(
      '/// Provides getters for all known modifier names. Values default to 0',
    )
    ..writeln('/// when not present in the underlying map.')
    ..writeln('@immutable')
    ..writeln('class ModifiersBase {')
    ..writeln('  const ModifiersBase(this.values);')
    ..writeln()
    ..writeln('  /// The underlying modifier values map.')
    ..writeln('  final Map<String, num> values;')
    ..writeln()
    ..writeln('  /// True if no modifiers are present.')
    ..writeln('  bool get isEmpty => values.isEmpty;')
    ..writeln();

  // Generate a getter for each modifier name
  for (final name in sortedNames) {
    buffer.writeln(
      "  num get ${lowercaseCamelFromSnake(name)} => values['$name'] ?? 0;",
    );
  }

  buffer.writeln('}');

  return buffer.toString();
}
