// Generates lib/src/types/modifier_names.dart with constants for all modifier
// names found in the Melvor JSON data files.
//
// Run from the logic/ directory:
//   dart run tool/generate_modifier_names.dart

import 'dart:io';

import 'package:logic/src/data/cache.dart';

void main() async {
  final cache = Cache(cacheDir: defaultCacheDir);

  try {
    print('Loading JSON data files...');
    final demoData = await cache.ensureDemoData();
    final fullData = await cache.ensureFullData();

    // Collect all unique modifier names
    final modifierNames = <String>{};
    collectModifierNames(demoData, modifierNames);
    collectModifierNames(fullData, modifierNames);

    print('Found ${modifierNames.length} unique modifier names.');

    // Generate the Dart file
    final output = generateDartFile(modifierNames);

    // Write to lib/src/types/modifier_names.dart
    final outputFile = File('lib/src/types/modifier_names.dart');
    await outputFile.writeAsString(output);

    print('Generated: ${outputFile.path}');
  } finally {
    cache.close();
  }
}

/// Recursively collects all modifier names from a JSON structure.
void collectModifierNames(dynamic json, Set<String> names) {
  if (json is Map<String, dynamic>) {
    // Check for modifiers at this level
    final modifiers = json['modifiers'];
    if (modifiers is Map<String, dynamic>) {
      for (final key in modifiers.keys) {
        // Skip special keys like "add" which contain nested modifiers
        if (key == 'add') {
          if (modifiers[key] is Map<String, dynamic>) {
            collectModifierNamesFromMap(
              modifiers[key] as Map<String, dynamic>,
              names,
            );
          }
        } else {
          names.add(key);
        }
      }
    }

    // Also check enemyModifiers and playerModifiers
    final enemyModifiers = json['enemyModifiers'];
    if (enemyModifiers is Map<String, dynamic>) {
      collectModifierNamesFromMap(enemyModifiers, names);
    }

    final playerModifiers = json['playerModifiers'];
    if (playerModifiers is Map<String, dynamic>) {
      collectModifierNamesFromMap(playerModifiers, names);
    }

    // Recurse into all values
    for (final value in json.values) {
      collectModifierNames(value, names);
    }
  } else if (json is List) {
    for (final item in json) {
      collectModifierNames(item, names);
    }
  }
}

/// Collects modifier names from a modifiers map, handling nested "add" keys.
void collectModifierNamesFromMap(Map<String, dynamic> map, Set<String> names) {
  for (final key in map.keys) {
    if (key == 'add') {
      if (map[key] is Map<String, dynamic>) {
        collectModifierNamesFromMap(map[key] as Map<String, dynamic>, names);
      }
    } else {
      names.add(key);
    }
  }
}

/// Generates the Dart file content with all modifier name constants.
String generateDartFile(Set<String> names) {
  final sortedNames = names.toList()..sort();

  final buffer = StringBuffer();

  // Header
  buffer.writeln('// GENERATED FILE - DO NOT EDIT');
  buffer.writeln('//');
  buffer.writeln('// Generated by: dart run tool/generate_modifier_names.dart');
  buffer.writeln('//');
  buffer.writeln(
    '// This file contains constants for all modifier names found in the',
  );
  buffer.writeln('// Melvor Idle JSON data files.');
  buffer.writeln();
  buffer.writeln('// ignore_for_file: constant_identifier_names');
  buffer.writeln();

  // Class with constants
  buffer.writeln('/// Constants for modifier names used in the game data.');
  buffer.writeln('///');
  buffer.writeln(
    '/// These match the keys found in "modifiers" objects in the JSON.',
  );
  buffer.writeln('abstract final class ModifierNames {');

  for (final name in sortedNames) {
    buffer.writeln("  static const String $name = '$name';");
  }

  buffer.writeln('}');

  return buffer.toString();
}
